### ISSUE TITLE
[QUESTION] Count Steps 24/7

### ISSUE THREAD

**Issue by osyyyS** [jfversluis/Plugin.Maui.Pedometer#3]
Hi, I was wondering if it is possible to always count the steps even when the user doesn't have the app launched, or is there any advice on how to do so? 😁

**Comment by jfversluis** [comment]
Not with how this is implemented, at least not on iOS. See: https://stackoverflow.com/questions/28072009/can-i-listen-to-cmpedometer-in-the-background-and-send-a-local-push-notification
